### ISSUE TITLE
Enhancement:  Player Tab

### ISSUE THREAD

**Issue by m9115m** [bwentzloff/afs#102]
This is likely an overhaul to the tab, but maybe not...

Suggest pulling down all the Player data when you load the page (either when loading Dashboard, or when switching to the Player tab).

Then selecting from the drop down does a filter of the local data, rather than a callback.

**Comment by bwentzloff** [comment]
That's how it's currently happening

**Comment by m9115m** [comment]
Is that also true of changing the values of the drop downs?  It looks like when the drop down value changes, the page does a callback.

**Comment by m9115m** [comment]
I think the issue my league is seeing is a browser compatibility issue.  So far, here's what AFS looks like in various browsers (maybe I should open up a separate cross browser compatibility issue)
1.)  IE11  Blank Page (Can't see anything)
2.) Firefox - Extremely slow callbacks (like in minutes at times) - almost unusable
3.) Safari Mobile -  Extremely slow callbacks (like in minutes at times) - almost unusable 

In Chrome, everything seems fine.  At little sluggish at times, but definitely usable.

**Comment by bwentzloff** [comment]
ok, thanks for the details. I'll take a look. Just a heads up, it's probably not likely we'll get around to supporting IE11. Is it possible that person can use Edge?

**Comment by bwentzloff** [comment]
Also, I just tried in Firefox and Safari and it worked great. I'll still keep investigating, just pointing out it may be an issue with a plugin or extension and not the browser itself. There were also some optimizations pushed out this morning, so if the page hasn't been refreshed today in those browsers, it's probably worth giving that a try.

**Comment by bwentzloff** [comment]
Thanks to @billwert there should be a significant improvement in performance today after a page refresh

**Comment by m9115m** [comment]
Performs well now on all browsers I've tested, on Windows, Mac, and Linux.   There a couple of UI init bugs with Matchups and Roster not populating, but I'll create new bugs with the details for those.

Thanks again for a great app
