### ISSUE TITLE
Re-export/anonymize the DB in SQLITE format

### ISSUE THREAD

**Issue by unRARed** [bwentzloff/afs#105]
@bwentzloff think you could re-export the DB as SQLITE from you MySQL admin interface? I'm trying to setup a seeder to use the dump, so we can run `php artisan db:seed` to be up and running quickly for local dev. However, sqlite doesn't like the export as is, nor have I been able to convert it with the various ways I've tried.

**Comment by bwentzloff** [comment]
Yeah, that would be great. The production database is way too big now to put in Github. I’ll see if I can export one of my local instances as SQLite.

**Comment by unRARed** [comment]
Yea, that would be even better. If you do that, providing a "test" username/password pair would be ideal. Perhaps different test pairs for the various "states":

- League commish
- Regular user
- others?

**Comment by bwentzloff** [comment]
Yeah. That’s the plan. Just a head’s up: I probably won’t have this done today but I’ll try to get it done first thing in the morning.
