### ISSUE TITLE
Question:  When does the process that auto fills the line up from the previous week run?

### ISSUE THREAD

**Issue by m9115m** [bwentzloff/afs#119]
Currently my line ups for week 5 are blank.

When does the job run that auto populates them?

Suggestion:  After the scores are finalized for a week, run the job that copies the line up from the previous week over.

**Comment by bwentzloff** [comment]
They should be there now

**Comment by m9115m** [comment]
There's still an issue with one team in my league, oddly.  One team did not automatically copy over from the previous week. The team name is Bubbaganoosh.  League 5284

**Comment by m9115m** [comment]
Also had a similar issue this week with the auto populate job.

I have two teams that didn’t completely autopopulate.  League number 5284, team names Apex_XFL2020 and The Scurvy Dogs. Apex_XFL2020 only populated one player Sam Mobley and The Scurvy Dogs matchup roster was completely blank. All the players on both teams appear as expected on the Roster tab.

Theory
Perhaps a field in the database is not set correctly for the players on these two teams.  And, Somehow during the autopopulate job, some/all players on these teams are excluded from the autopopulate query, which adds them to match up roster for the upcoming week


Thanks again for a great app
