### ISSUE TITLE
Bug:  Process Waivers is visible when Show Commish Tools is unchecked

### ISSUE THREAD

**Issue by m9115m** [bwentzloff/afs#121]
STR:
Navigate to the Dashboard
Note that Commish Tools is unchecked
(expected Process Waivers to be hidden)
<see screen shot>
![Capture](https://user-images.githubusercontent.com/16707058/75815366-22bc0f80-5d48-11ea-98f9-4f9cc72d62d9.PNG)

**Comment by bwentzloff** [comment]
It was hidden initially when that feature first came out, but I got a ton of messages saying people could no longer figure out how to process waivers. I figured that at this point in the season, it’s probably the most common task for commissioners, so we would have it visible all the time.

**Comment by m9115m** [comment]
Got it.  I was seeing some strange behavior, where it seemed like the Process Waivers tab would not refresh unless Show Commish Tools was checked.  Now I can't reproduce it. :)

Thanks again for the great site.

**Comment by bwentzloff** [comment]
Yeah, that was a bug I fixed earlier today. Glad to hear it’s working now.
