### ISSUE TITLE
Scrape inactive list and show inactive players in lineups

### ISSUE THREAD

**Issue by bwentzloff** [bwentzloff/afs#131]
https://www.xfl.com/en-US/inactives

**Comment by m9115m** [comment]
Are you thinking of scraping https://www.xfl.com/en-US/xfl-injury-report?  I was going to submit this as an enhancement.  :+1:  Right now, I manually look through the report each week and let my league know if they have any players in their line up that are Out or Questionable.

**Comment by bwentzloff** [comment]
Yeah, hoping to have that done this weekend.

**Comment by m9115m** [comment]
Hey man,

Glad to know that you’re still alive. :-)

What’s the plan for the XFL fantasy page? The XML is back in 2022
