### ISSUE TITLE
Unable to initiate draft process

### ISSUE THREAD

**Issue by kenjdavidson** [bwentzloff/afs#132]
I'm attempting to use the new `dev-snapshot.sql` seed in order to help out with some of these issues/requests.  But I'm unable to initiate the drafting process - I haven't combed through the code yet, but I'm curious if there are steps missing?

With regards to the current readme and data:
- I had to Truncate the `migrations` table after running the migrations and then attempting the seed
- I had to comment out the creation of the INDEX lines in order for the seed to proceed

Once that got done everything started up. I reset the draft order so `user1` was first, thinking that this would help.  Going to keep going through, but if you could point me to something that might be missing it would be cool.

**Comment by bwentzloff** [comment]
There is a cron job that advances drafts. You need to hit the /api/v1/league/updateDraftStatus/ endpoint in order to advance the draft.

**Comment by kenjdavidson** [comment]
Ah, I didn't see anything in the source to setup as a cron.  I'll take a look for this next time I load it up.

**Comment by bwentzloff** [comment]
For testing purposes locally, I just hit the URL in a browser, I don’t bother setting up a cron.

**Comment by kenjdavidson** [comment]
Makes sense. I was just too lazy last night to start looking through without a hint of where to go.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
