### ISSUE TITLE
Urgent Bug:  The site seems to have reverted to week 3's standings

### ISSUE THREAD

**Issue by m9115m** [bwentzloff/afs#135]
Yesterday our league saw the results from Week 5 on League Home.  Today the site has reverted to Week 3's standings on League Home.

Not sure if it's just our league.  5284

**Comment by bwentzloff** [comment]
I just checked and all your data is still there. I’ll look into this and try to figure out what happened. It should recalculate with the correct standings in the next few hours.

**Comment by m9115m** [comment]
Thanks for checking.

League Home is still showing week 3

**Comment by m9115m** [comment]
League Home is showing week 5 again. Thanks
