### ISSUE TITLE
Can't start a specific player

### ISSUE THREAD

**Issue by bkonicek** [bwentzloff/afs#15]
I'm unable to start Mekale McKay (WR) in either an open WR or FLEX position. Every other player works fine.

**Comment by bwentzloff** [comment]
Thanks for using Github issues for this :) Could you give me a little bit more info:
1) Are you seeing the Start button and it just doesn't do anything or are you not seeing the start button at all
2) Could you let me know your league ID (it's in the URL of the page you're on)

**Comment by bkonicek** [comment]
Thanks! I'm seeing two options for this player - "Start at WR" and "Start at Flex". When I click either option the roster window refreshes but the player is still in the Bench. Doesn't make a difference if I remove all my other WRs first or not. The league ID is 9742.

**Comment by bwentzloff** [comment]
I'll continue to investigate. In the meantime, I tried locally to start him like 4 times and the first three had the same behavior then he just sort of worked the fourth time. Could be a result of the current overloaded servers.

**Comment by bkonicek** [comment]
Sounds good, definitely could have been the server load, just weird it was
the same player every time. I'll try starting him again a bit later and see
if it works.

**Comment by Fricksta** [comment]
Whole site is slammed we are all having same problems

**Comment by bkonicek** [comment]
Just to update - I tried again this afternoon and still couldn't start McKay. It let me bench someone in a WR slot, but had the same problem, and ended up putting the player I benched back in.

**Comment by MattWhilden** [comment]
We saw weird behavior like this and noticed that player being on two rosters at the same time. Maybe that's a red herring but may help get this chased down.

**Comment by bkonicek** [comment]
Thanks @MattWhilden , unfortunately I've looked over all the rosters in our league and that doesn't seem to be the case in this situation. He's not showing up in the "No Team" roster either, so he's definitely assigned to only my roster.

**Comment by bkonicek** [comment]
Unfortunately I still can't start McKay in Week 2, even if I remove everyone in my lineup and try to start him first...

**Comment by bwentzloff** [comment]
Could you let me know your League ID (it’s the number in the URL of your league’s webpage)?

**Comment by bkonicek** [comment]
Sure, it's 9742. I can also going to try dropping him and picking him back up again to see if that does anything.

**Comment by bwentzloff** [comment]
Yes, that’s a quick fix for it. I’ll continue investigating why it happened in the first place, but you can always unassign him from a team on the Players tab, then place him back on the correct team and that should work.

**Comment by bkonicek** [comment]
Yup, that did it. Guessing it was something that happened during the draft that didn't completely add him to my roster in the backend. Thanks for the help!

**Comment by bkonicek** [comment]
Turns out one of the other players in the league DID also have him - looking at the draft queue he picked him then I immediately picked him after. Somehow when I dropped him from my team it also dropped him from the other player, and then I was allowed to claim him.
