### ISSUE TITLE
Site down for over an hour - can't set lineups for today's games.

### ISSUE THREAD

**Issue by smoothlarryhughes** [bwentzloff/afs#16]
is there a server issue causing us not to be able to login into the site to set lineups?

**Comment by smoothlarryhughes** [comment]
this is infuriating...no one in my league can do anything on this site...its basically useless at the moment.

**Comment by Fricksta** [comment]
Larry im having the same problems I'm guessing we are gonna have to wait until week 2 .. seems like too many people are still trying to last min draft. The site admin should have stopped the ability to draft by 11am, so that way people could sit and actually utilize the site to get their rosters set

**Comment by guldmand** [comment]
Today I wanted to login and:

1. **drop** two players
2. **add** two free agent players to my team
3. change two players in my **week1 lineup**
_but none of the above was possible._

**How** are we supposed to play fantasy football when "**Players**", "**Rosters**" & "**Matchups**" isn't working ?

**Comment by Fricksta** [comment]
Lol ya I get it's not ESPN or Yahoo ... But maybe he wasn't expecting this much hype on his page and it overloaded his expectations.. but you are def correct when I login I'm lucky to see my teams roster .. I filled out my starting lineup last night and today it isn't showing so I'm hoping it worked.. all I did for my group is had everyone post their lineups on our messenger group with hopes that by next week this is all fixed..

**Comment by BallisticNick16** [comment]
I can’t get to my league, whenever I click the link it gives me an error, same thing happens for everybody in my league. And there’s no other way to get to the league, it’s like it got deleted somehow, but nobody deleted it

**Comment by Fricksta** [comment]
You just gotta keep refreshing and possibly logging back in.. it's annoying indeed but that's what works for me.

**Comment by rwtuck95** [comment]
Hell get it fixed.. It was like this last year for the AAF... Im sure it didnt get deleted... give him some time!
