### ISSUE TITLE
It says Error, can not register at the moment. If the problem persists, please contact an administrator when I try and sign up.

### ISSUE THREAD

**Issue by Nstaudt19** [bwentzloff/afs#17]

**Comment by Nstaudt19** [comment]
Cant sign up

**Comment by smoothlarryhughes** [comment]
same here - can't get onto the site to set lineups.  We just finished out draft and can't get onto the site now and I have to make some roster changes as the commish.  The site also let one of our guys draft an individual QB even though we have everything set up as TEAM QB
