### ISSUE TITLE
How can commish set someones lineup?

### ISSUE THREAD

**Issue by smoothlarryhughes** [bwentzloff/afs#18]
How can commish set someones lineup?

**Comment by Fricksta** [comment]
Right now it just seems like the whole site isn't workable.. at like 1 am yesterday as the commish I was able to view lineups and then click the players on other teams to start.. but as of now the traffic seems to be too overwhelming for this guy's service

**Comment by smoothlarryhughes** [comment]
didn't know so many degenerates would be interested in XFL fantasy!  lol

**Comment by Fricksta** [comment]
Lol right unless this site is being hosted off Verizon 5G lol but ya it's pretty crazy IDK how we finished our draft last night lol

**Comment by smoothlarryhughes** [comment]
my draft was 10:30 this morning and worked fine and as soon as the draft was over everything went down

**Comment by Fricksta** [comment]
We drafted at 8pm yesterday lol had to refresh and login 10 times per pick was crazy now can't login to see rosters or set lineups before 2 pm games

**Comment by jbower63** [comment]
Many of us can't set lineups
