### ISSUE TITLE
Garbage fucking service

### ISSUE THREAD

**Issue by ghostaccount12345666** [bwentzloff/afs#19]
This piece of crap has been down all day

completely ruined our draft this afternoon - took all the fun out of everything

why even put this out if it was so truly unfit for the job. my goodness. thanks for wasting our fucking time and ruining our chance to play this season.

seriously, were you the dude who made the Iowa Caucus app too? wouldnt surprise me.

you should just delete this entire repo. lest a prospective employer find out how pathetic your work is.

**Comment by ghostaccount12345666** [comment]
@bwentzloff

**Comment by joshkostal** [comment]
This application was made by a person who is taking their time and money to give you a service. It may not be the best, but it’s better than any other platform out there.

You should have read the warning that stated the site would be overloaded today and planned accordingly. Your failed draft is on you alone.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by punchoutnd** [comment]
The developer is providing a service to you at no cost, be patient with it. Granted, it should have been started sooner bu noone here knows the time restrictions or other projects he has. I appreciate the job, and yes, it has a long way to go. We need players locked once games start, waivers, times dates of games, team players are on in matchups, transaction list with date time, etc...but I have patience and we hope

**Comment by ababcock1** [comment]
Yes this service was about the same in the AAF they will get the bugs worked out as they did in the AAF
