### ISSUE TITLE
Joke

### ISSUE THREAD

**Issue by zniddy** [bwentzloff/afs#29]
Killing half your viewers right off the bat. First question, who will watch players they don’t know?Fantasy Football Leagues!!!! The builders of the FF site Must be the same people responsible for counting ballots in Iowa.

**Comment by joshkostal** [comment]
>Killing half your viewers right off the bat. First question, who will watch players they don’t know?Fantasy Football Leagues!!!! The builders of the FF site Must be the same people responsible for counting ballots in Iowa.

@zniddy This application was not built by the XFL. This is a person doing it for free (notice no ads). Be thankful that you have a platform to use at all.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
