### ISSUE TITLE
Set roster yesterday morning/afternoon and now it is showing that I didn't set it.

### ISSUE THREAD

**Issue by pmurphy76** [bwentzloff/afs#30]
If I set my roster and now it is saying I didn't then how is anyone going to trust this site.

**Comment by joshkostal** [comment]
Can confirm this happened to me as well

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Da-BIG-Boss** [comment]
Same here, I've effectively lost the game because of the lineup drop now...

**Comment by ababcock1** [comment]
Same here and all but one came back but still a problem
