### ISSUE TITLE
Set Lineup Q

### ISSUE THREAD

**Issue by jneub07** [bwentzloff/afs#39]
Hi,
First, thanks for doing this ... I’m sure it’s a PIA. 

Q: we had issues drafting before week 1 due to learning curves so we redrafted last night to start fresh week 2. Now when we review our lineups to set the lineup for week 2, we see the players on our bench who we just drafted, as well as the players from our first draft? We can’t set lineups because of this. Any thought on how to fix this? I’m not seeing a way in commish tools. My next thought is to recreate a new league entirely and hand place each player from the draft and place on each team myself... which I want to avoid!

Reference:

https://altfantasysports.com/league/view/12733

5e3e4ce71723d/

Thank you!

**Comment by bwentzloff** [comment]
The commissioner can adjust lineups on the Players tab.

**Comment by jneub07** [comment]
Hi, thanks for the speedy reply! 

 I think it’s a bit more complicated. When I view my team as commish I cannot see the players I need to remove. Examples attached.

![A3D05007-E49B-42F4-BEBE-22C7995042F3](https://user-images.githubusercontent.com/60885489/74161620-382c9680-4bed-11ea-9b4a-bb1727af4d44.png)
![3BF9376D-6333-4023-A3DB-79DC217FD614](https://user-images.githubusercontent.com/60885489/74161622-382c9680-4bed-11ea-9cb4-0e671f40a06f.png)
![6FC638D0-5746-4C1A-9D3C-3B8F1235C375](https://user-images.githubusercontent.com/60885489/74161624-38c52d00-4bed-11ea-91d4-6de828f35107.png)

**Comment by bwentzloff** [comment]
Take a look at the Players tab. If you're the commissioner, you'll see a Commish Tool called "Assign Team". You can use that to drop players from teams.

**Comment by jneub07** [comment]
Hi, I might not be explaining this properly. So, under Players everything shows correctly - players are on the proper teams (for example Dungey as shown isn’t showing on my team so I don’t need to move him). However, when I view Matchup/Set my lineup, I see Dungey on my squad - among others - and I cannot get rid of him in order to put players from my bench into my live lineup. These players are from our 1st draft. Does that make sense? Again, apologies if I’m being confusing.
![702B5488-40D8-4424-9E86-47DA2242DDED](https://user-images.githubusercontent.com/60885489/74163363-47611380-4bf0-11ea-9749-e26d614bb2b4.png)
![DA1BFC0A-1BF5-4D9B-8AB9-E200A930CBEA](https://user-images.githubusercontent.com/60885489/74163366-47f9aa00-4bf0-11ea-9ea4-75c3a45b97b1.jpeg)

**Comment by bwentzloff** [comment]
Oh ok. Yes, that makes more sense. A quick fix would be to unassign the player from any team (choose the "No Team") option, then add him back to the proper team. That should take care of it.

**Comment by jneub07** [comment]
Cool! I think that worked. TY! 

Last q: we are considering killing TEs. Can I make that change after the fact now without creating issues?

**Comment by IdCleric** [comment]
I think I found what causes this behavior: when you have two position slots, e.g. RB1 & RB2, and you bench the first (RB1), the second will now show in the RB1 slot and the bench button will not work.  My guess is that the button is sending a message to bench the player _shown_ in the RB1 slot while the backend sees that slot as empty, and therefore correctly does nothing, because the player is still "in" the RB2 slot.
