### ISSUE TITLE
Commissioner Waiver Control?

### ISSUE THREAD

**Issue by Ace1234NY** [bwentzloff/afs#40]
Hello,
Thanks for all you do on the site. This is more of a suggestion, but would love to have commissioner control of the waiver priority. Some people prefer waiver priority to run reverse of standings, but others want a system of "use it and lose it" where a successful claim puts you at the back of the line. If the commissioner had control over the waiver order, we could all create the waiver system that our leagues prefer. I do also hope that after waivers are run on our specified day, the unclaimed players will become free agents until gametime.

Thanks again.

**Comment by bwentzloff** [comment]
Great suggestion. Thank you.

**Comment by ababcock1** [comment]
Also after waivers is it first come first serve??
