### ISSUE TITLE
Create snapshot of historical and/or dummy data to develop against.

### ISSUE THREAD

**Issue by josheverett** [bwentzloff/afs#42]
I'd like to contribute to this project, but having to manually populate your local DB with game/player/etc. data is a big ask for more lightweight contributions.

An optional data fixture import/migration/whatever, made available to developers as part of this repo, would significantly lower the barrier to entry for making quick (but valuable) fixes to the product.

**Comment by bwentzloff** [comment]
I'll get a SQL dump out there (with user info removed)

**Comment by unRARed** [comment]
We should be able to leverage Seeders and Factories to generate a bunch of dummy data.

**Comment by bwentzloff** [comment]
I added a SQL dump to the root directory: example_database.sql
