### ISSUE TITLE
League Standings

### ISSUE THREAD

**Issue by tag60** [bwentzloff/afs#48]
Hi Brian - first off thanks so much for putting together season long, XFL fantasy on the AltFantasySports website!!  Really appreciate it.  The site has some great improvements since last year when you hosted AAF.

Question - will the standings on the home page for each league be checked for accuracy?  Our reflect the current win - loss for each team but aren't accurate for league standings.

Thanks again!

**Comment by bwentzloff** [comment]
Yes, they are currently not ordered. That will be fixed shortly.
