### ISSUE TITLE
Retroactively setting week one lineups

### ISSUE THREAD

**Issue by tclarencebrown** [bwentzloff/afs#49]
We drafted last night and would like to set week 1 rosters, if possible.  I started to this morning but all of a sudden I couldn't anymore.  Help please.

**Comment by bwentzloff** [comment]
Week 2 just started this morning, so even if you set the lineups, the scores won’t be calculated. I can definitely add this functionality, but it will most likely take a few days to get to it.

**Comment by tclarencebrown** [comment]
Thanks.  I’ll check back in a few days.
