### ISSUE TITLE
WAIVERS / UNLOCK PERIOD

### ISSUE THREAD

**Issue by smoothlarryhughes** [bwentzloff/afs#51]
can you make players fully unlocked for pickup after the waivers run and until their games start so that owners can make changes to their roster more than once a week?

**Comment by bwentzloff** [comment]
Yes, this already happens

**Comment by hotnickels** [comment]
Really not intending to pile on, just in case it hasn't been brought up elsewhere yet:
after waivers processed this morning, the players dropped are still seemingly locked into the week 2 lineup via the matchup tab, so lineup changes as a result of the waivers cannot yet be applied for week 2.
Thank you for this platform!!
