### ISSUE TITLE
PROPS! Transaction History/current Waiver wire explained

### ISSUE THREAD

**Issue by RoyalRumbleFFL** [bwentzloff/afs#56]
- Thank you for being THE ONE that had the guts to build a XFL fantasy league hosting website!  What would we have done without you?  
- Would it be possible for you to add a transaction history page (with add/drops, waiver wire moves, and trades)?  
- could you explain how waivers are divided up between teams in the current system? Is there a waiver order?
Thanks again!

**Comment by bwentzloff** [comment]
Yes, transaction history is coming this week along with a lot more control over how waivers work.

**Comment by punchoutnd** [comment]
Sorry, I posted the transaction history issue again, didnt read first

**Comment by RoyalRumbleFFL** [comment]
I'm sorry to ask again but our league hasn't been able to clearly understand how the waivers are prioritized at this point.  Is it a rotating priority (once you get the pick you go to the end of the line)?  If so, How can we tell who is the 1st, 2nd, 3rd etc. in order?
Thanks

**Comment by jondaku** [comment]
So waivers will be sort out before wednesday?  I dont even see the team waiver orders so how can I know who has the priority if two teams put in a claim for the same player?

**Comment by bwentzloff** [comment]
On the Process Waivers tab, if you don’t see any waiver claims, that means none have been made.

**Comment by jondaku** [comment]
When they are they dont show the waiver order, this is the issue!

**Comment by bwentzloff** [comment]
Right, each league determines their own waiver order and the commissioner executes on it.

**Comment by RoyalRumbleFFL** [comment]
To help other commissioners... 
Bwentzloff stated above that we need to keep track.  

I put out a list on Saturday morning of the waiver order for the weekend .  

One problem I notice as Comish is... 
knowing what other owners submitted made me think differently about the order of waivers that I was putting in (knowing that I wasnt going to get a guy).  There could be several reasons like that that would make it good for the site to eventually do the waiver order for us.  So that it doesn't compromise 
 the integrity of Comish equality with other league owners.

**Comment by punchoutnd** [comment]
Sir,Are you going to run a USFL host this year? Hope so

Sent from Yahoo Mail on Android 
 
  On Tue, Mar 3, 2020 at 12:11 PM, ***@***.***> wrote:   
Closed #56.
