### ISSUE TITLE
Waiver Wire / Player Scores

### ISSUE THREAD

**Issue by XFLFantasyFan** [bwentzloff/afs#57]
First, thanks so much for your hard work in getting this going.  Just a couple of things I wanted to ask about.

Is there a specific time that waivers process? Ours were supposed to go through this morning but don't seem to have done so yet.

Also, is there any way to be able to show player's score histories? Or have the "View Matchup" box show the scores for players that were on the bench? 

Thanks!

**Comment by d1desade** [comment]
Waivers n my league didn't go through this morning and all available players are still on waivers.

**Comment by bwentzloff** [comment]
Waivers are processed by the commissioner.

**Comment by d1desade** [comment]
Hi. I only see my waivers as commissioner in the pending waivers. If others were trying to claim someone would I be able to see them also?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by bwentzloff** [comment]
Yes, the Process Waivers tab will show you all pending waivers.

**Comment by d1desade** [comment]
Thanks.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
