### ISSUE TITLE
Commish won all waivers

### ISSUE THREAD

**Issue by obryant13** [bwentzloff/afs#59]
I'm commish of our league and won all 5 waivers with a low waiver priority this morning, league mates think I cheated....anyway to fix other than dropping playing and doing manual offline waivers this week?? Thanks for the work on the site btw!

**Comment by d1desade** [comment]
I might have had the same issue. All 3 of my waivers moves went through but not sure if anyone else tried claiming.

**Comment by obryant13** [comment]
I'm sure my guys had waivers in, worst part now is they all know who I wanted to pick up now if we do offline waivers and I won't get anyone lol

**Comment by obryant13** [comment]
Here's the link if needed, kind of a big deal here in a money league.....
https://altfantasysports.com/league/view/1585

**Comment by commisonergordon** [comment]
Fellow commish here, I believe I have the same issue. Is there gonna be a way to revert the previous transactions or any other suggestions?

Btw great job so far On building this league.

**Comment by bwentzloff** [comment]
Yes. Commissioners can now retroactively set lineups and process waivers manually

**Comment by bwentzloff** [comment]
And you can already assign players to teams on the Players tab to move players from bad waiver claims today.

**Comment by obryant13** [comment]
Any way to know what the teams waiver order was or what claims they had tried to make ? Otherwise integrity is compromised and I suppose everyone gets a refund and it's over for til next year
