### ISSUE TITLE
Waiver priority. 

### ISSUE THREAD

**Issue by djhXFL** [bwentzloff/afs#60]
Great work so far!! Love this site. Appreciate all the hard work! 
 Our Waivers will run on Thursday’s. Do you know what process it will follow? I know us not being able to put a priority on teams of who gets first pickups is available yet but I was just wondering what process it is going by until it gets fixed? 
Thanks again! 👍🏼👍🏼

**Comment by bwentzloff** [comment]
Waivers are now processed manually by the commissioners.

**Comment by djhXFL** [comment]
Thanks! Just put them through & it worked perfectly. Thanks again for the work you’re doing. 👍🏼
