### ISSUE TITLE
Dropped players previous score removed??

### ISSUE THREAD

**Issue by d1desade** [bwentzloff/afs#61]
If you drop a player during waivers it removes their score from previous weeks game score.

**Comment by bwentzloff** [comment]
Could you let me know your league ID (the number in the URL of your league) and I'll take a look?

**Comment by d1desade** [comment]
The league number is 14352

**Comment by d1desade** [comment]
I dropped LA's backup QB via Week 2 waivers, whom I had started in Week 1.

**Comment by bwentzloff** [comment]
This is a bug that has been fixed. It won’t happen again. However, your commissioner will have to fix your lineup from week 1. They can add the LA QB back to your roster temporarily, add him back to your week 1 lineup, then remove him from your team again.

**Comment by d1desade** [comment]
Worked perfect. Thanks

**Comment by bwentzloff** [comment]
I'm actually going to leave this open for a little bit so if there are others with similar problems they can easily see the solution.

**Comment by tag60** [comment]
Had the same problem but the fix worked.
