### ISSUE TITLE
would like to delete results from week one

### ISSUE THREAD

**Issue by brickhouse75** [bwentzloff/afs#63]
Had drafted after the first week and some of the teams set their lineups, wondering if there is a way for the commish to reset the win totals so we all start the league off with no wins and no losses. Thank you

**Comment by bwentzloff** [comment]
Yeah. The commish can go in and bench everyone on week 1

**Comment by brickhouse75** [comment]
Thank you!

**Comment by jondaku** [comment]
For some reason I cant remove all players, it wont allow me to make score 0 for any team.   I placed all teams on by week for week 1 but it is still showing scores and wins and losses on the main league page, any advice?

**Comment by jondaku** [comment]
I managed to get all week 1 scores to 0 and I even set all the matchups to “no team” but it is still showing wins and loses for that week on the main page.  How can I fix this?

**Comment by bwentzloff** [comment]
It can sometimes take a few hours for the standings to update. This is because it’s a somewhat resource intensive process since we now have over 50,000 leagues on the platform so a process is running on the server that only calculates a few leagues at a time. If it’s not updated in the next 3 hours, let me know and I’ll go in there manually and update it.

**Comment by jondaku** [comment]
It’s still showing the a  win and loss that shouldn’t be there.

> It can sometimes take a few hours for the standings to update. This is because it’s a somewhat resource intensive process since we now have over 50,000 leagues on the platform so a process is running on the server that only calculates a few leagues at a time. If it’s not updated in the next 3 hours, let me know and I’ll go in there manually and update it.
> […](#)
> On Feb 19, 2020, at 8:30 AM, jondaku ***@***.***> wrote: ﻿ I managed to get all week 1 scores to 0 and I even set all the matchups to “no team” but it is still showing wins and loses for that week on the main page. How can I fix this? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by bwentzloff** [comment]
Could you copy/paste the link to your league and I'll take a closer look?

**Comment by jondaku** [comment]
https://altfantasysports.com/league/invite/5e3b3a681ea8f/

**Comment by bwentzloff** [comment]
Thanks, it will probably show all 0’s now. It will be recalculated from scratch the next time around and everything should look correct later this afternoon.

**Comment by jondaku** [comment]
Having another problem, Matt Jones was picked up off waivers, he is showing on the team roster but not showing up in the matchup page.

**Comment by bwentzloff** [comment]
Should be there now.
