### ISSUE TITLE
Waived players still in Week 2 lineup

### ISSUE THREAD

**Issue by BananaBreadatWerk** [bwentzloff/afs#66]
I set my lineup at the beginning of the week. Through the waiver process, I dropped my TE and D/ST. They are no longer listed on my roster. However, when I go to update my lineup in the Matchup tab, the players I dropped are still listed in my starting lineup. It will not allow me to remove them from my starting lineup. 

Any recommendations?

**Comment by bwentzloff** [comment]
Some people didn’t have a dropped player removed from their lineup. The commissioner can fix this by unassigning the player from their current team then reassigning him to the same team.

**Comment by bwentzloff** [comment]
Sorry, just realized that response doesn’t work because you already dropped the player. Give me a few minutes.
