### ISSUE TITLE
Transactions

### ISSUE THREAD

**Issue by punchoutnd** [bwentzloff/afs#68]
Great job on the site and it is appreciated. Can you add to your list of to do's:
1. Transaction list. Owners be able to view all transactions made
2. Commish message area. A way for commissioners to post info and notes on main page.
3. Lineup details. When setting lineups owners see who that player opponent is for the week
Thanks

**Comment by bwentzloff** [comment]
These are all the next 3 things on the list :) you should see them in the coming week.

**Comment by punchoutnd** [comment]
Great service! Thanks for all the work. To bad the XFL closed, but we thank you for what you did.

**Comment by chalbersma** [comment]
👍

**Comment by bwentzloff** [comment]
I’m confident spring football will be back at some point in the future! AltFantasySports will be ready to go when it is :)

**Comment by punchoutnd** [comment]
Have you ever considered making a fantasy site where the games are simulated rather than real players? Owners would interact as normal, add, drops, trades, etc. The simulations could be an ai on pc, madden, etc. And commissioners could elect the sim and input the stats. Something along that lines. Basicly fantasy leagues based on simulated games.

Sent from Yahoo Mail on Android 
 
  On Tue, Apr 21, 2020 at 3:50 PM, Christopher R Halbersma<notifications@github.com> wrote:   


 👍
