### ISSUE TITLE
Xfl league

### ISSUE THREAD

**Issue by Irish187** [bwentzloff/afs#69]
I have been unable to pick a lineup. Or see stats on any of my players. The only thing I can do is drop players.

**Comment by bwentzloff** [comment]
Sounds like your league commissioner needs to hit the "Fix Matchups" button on the Matchup tab.

**Comment by Irish187** [comment]
I been bugging him since day one. When the draft shut down in round 1. Basically he said he's doing everything he can and for me to stop messaging him everyday.Russell McKinney453-4093
-------- Original message --------From: bwentzloff <notifications@github.com> Date: 2/14/20  2:28 PM  (GMT-07:00) To: bwentzloff/afs <afs@noreply.github.com> Cc: Irish187 <irishdeath187@gmail.com>, Author <author@noreply.github.com> Subject: Re: [bwentzloff/afs] Xfl league (#69) Sounds like your league commissioner needs to hit the "Fix Matchups" button on the Matchup tab.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/bwentzloff/afs/issues/69?email_source=notifications\u0026email_token=AOR434PJ4NFRZ6J4MFQDR4LRC4EGXA5CNFSM4KVP7Y52YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEL2PRGQ#issuecomment-586479770",
"url": "https://github.com/bwentzloff/afs/issues/69?email_source=notifications\u0026email_token=AOR434PJ4NFRZ6J4MFQDR4LRC4EGXA5CNFSM4KVP7Y52YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEL2PRGQ#issuecomment-586479770",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
