### ISSUE TITLE
Suggestion: Lineups able to be set for future weeks

### ISSUE THREAD

**Issue by unRARed** [bwentzloff/afs#70]
Maybe I'm not finding it, but it seems as if lineups can only be set for the current, upcoming matchup. 

Given the issues experienced last week with the server being over-allocated, it would be nice to set lineups for future matchups ahead of time. Even more ideal would be to always preload the following week with the lineup data from the prior matchup (unless the following week was already explicitly set).

**Comment by jondaku** [comment]
Yes I agree lineups should carry forward to the next  week so we can just change a few players and not have to individually add each position every week!
