### ISSUE TITLE
Suggestion: Separate altfantasysports.com requests from development issues

### ISSUE THREAD

**Issue by unRARed** [bwentzloff/afs#71]
It seems like it would be ideal to create a contribution guide for how feature suggestions / bugs should be reported here. As well, issues like "This thing in my league isn't working properly" might be served better from a discussion board / forum.

**Comment by bwentzloff** [comment]
All excellent suggestions. Thanks. I’ll add these all to the queue. I’m about to set up an issue board here too, which will help organize all the requests.

**Comment by unRARed** [comment]
Even some tagging would be nice to be able to easily see which issues are dev vs. app support.

**Comment by bwentzloff** [comment]
That seems like the quickest and easiest until some kind of support ticket solution is in place. It’s kind of nice when people can check here to resolve their own league issues sometimes as it cuts down on support issues a lot.
