### ISSUE TITLE
Defense score

### ISSUE THREAD

**Issue by punchoutnd** [bwentzloff/afs#75]
Maybe premature, but DC had 0 points allowed and it shows 1 point when it should be 10

**Comment by bwentzloff** [comment]
That stat line section is too vague and I need to clean it up to make it more clear. What it means is "1 instance of 0 points allowed, whatever that score is in your league settings". Not “1 point for 0 points allowed”. I’ll get that cleaned up soon to be more clear.

**Comment by punchoutnd** [comment]
Thanks

**Comment by punchoutnd** [comment]
Thanks
