### ISSUE TITLE
Can't see one team in league

### ISSUE THREAD

**Issue by firebreathingdragons** [bwentzloff/afs#77]
One of the drafted teams does not show up.. it was in the draft but now not listed in teams.  How can I fix that so that team shows up

**Comment by bwentzloff** [comment]
Let me know your League ID (it's the number in the URL of the webpage) and I can fix it for you

**Comment by firebreathingdragons** [comment]
Thanks for the help

https://altfantasysports.com/league/view/14585

The team we can do anything with his the Chestemere Chiefs

Ravi

Ravinder Pawar
canucks27@gmail.com
ravpawar@live.ca

**Comment by firebreathingdragons** [comment]
Brent,  Any luck on this request?  Thanks Ravi

**Comment by bwentzloff** [comment]
it should be fixed now.

**Comment by firebreathingdragons** [comment]
All good now thanksSent from my Samsung Galaxy smartphone.
-------- Original message --------From: bwentzloff <notifications@github.com> Date: 2020-02-18  12:36  (GMT-08:00) To: bwentzloff/afs <afs@noreply.github.com> Cc: firebreathingdragons <Canucks27@gmail.com>, Author <author@noreply.github.com> Subject: Re: [bwentzloff/afs] Can't see one team in league (#77) it should be fixed now.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/bwentzloff/afs/issues/77?email_source=notifications\u0026email_token=AOSLOTS5NCKJPLOAFX2SQWTRDRBELA5CNFSM4KWL6KC2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMETBKQ#issuecomment-587804842",
"url": "https://github.com/bwentzloff/afs/issues/77?email_source=notifications\u0026email_token=AOSLOTS5NCKJPLOAFX2SQWTRDRBELA5CNFSM4KWL6KC2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMETBKQ#issuecomment-587804842",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
