### ISSUE TITLE
How to replace a team with a new manager

### ISSUE THREAD

**Issue by bald777eagle** [bwentzloff/afs#80]
I had someone not managing there team. So I've found someone to take it over. What I need to know is if I click remove team does it remove the team completely? Or will it give me the option to send an email to the new owner? Should I remove all players remove team and then add new team add the players to the the new team then click fix matchups? Please help

**Comment by bwentzloff** [comment]
I can switch them out for you. Please email me at brian@altfantasysports.com <mailto:brian@altfantasysports.com> with the league info and the new user’s email address. Please don’t post user’s email addresses here, just contact me directly. Thanks.

**Comment by bald777eagle** [comment]
What league info do you need?

**Comment by bwentzloff** [comment]
Your league ID. It’s the number in the URL of the page.
