### ISSUE TITLE
Incorrect Scoring according to Rules

### ISSUE THREAD

**Issue by jcase0** [bwentzloff/afs#81]
My league (2175) has Rules set to score 6 pts per rec/rush TD and 4 pts per pass TD, however, the system is scoring 1 pt per all TDs.
Appears to be a bug. Is there a way to override or just wait for fix? Thanks for your work....

**Comment by bwentzloff** [comment]
Yeah, that area needs to be cleaned up and made more clear. It’s currently just showing the number of each stat that occurred, not the actual calculated score. So when it says “1.00 Receiving TD”, it means that player caught one touchdown and in your league will be worth 6 pts. It’s not saying “1.00 points for receiving td”.

**Comment by jcase0** [comment]
Gotcha, thank you for the clarification. Appears the same goes for Interceptions, Fumbles, Receptions, etc., anything with a 'count'. Yardage is actually the point total.

**Comment by bwentzloff** [comment]
Yardage isn’t the point total either. It’s the number of units of that yardage the got. So something like "5 10 yards rushing” means they ran for a total of 10 yards 5 times, or 50 yards
