### ISSUE TITLE
Commish Tool to Modify Matchup Scores?

### ISSUE THREAD

**Issue by sidnages** [bwentzloff/afs#83]
Are there any plans for a feature to allow commissioners to manually alter the scores of previous matchups? We’ve encountered an issue where some of us made waiver claims and dropped players who started the previous week. These players were then retroactively erased from the previous week’s matchups, messing up the scores.

**Comment by m9115m** [comment]
I think this might be fixed now.  I noticed that my League Home page updated, based on changes made in the past.
