### ISSUE TITLE
Lineup not rolling over from week to week

### ISSUE THREAD

**Issue by m9115m** [bwentzloff/afs#84]
Similar to the NFL fantasy leagues, it's a great feature to have your lineup automatically roll over from week to week.  That way, once you set your line up in Week 1, it's automatically populated for Week 2 (unless you drop a player), and each subsequent week going forward.

Any chance a batch job could run on Sunday night/Monday am that auto-populates the league line up for the upcoming week?

Thanks for a great app

**Comment by bwentzloff** [comment]
Actually I thought that was already happening. It must have errored out this week. I’ll get it fixed this week.

**Comment by m9115m** [comment]
Hey Brian,

Should we be expecting this week's lineup to automatically roll over to week 4?

Thanks

**Comment by bwentzloff** [comment]
Yes, that’s the plan.

**Comment by m9115m** [comment]
Appears to be fixed.  Had one team that didn't appear to be copied over, but will re-check next week.
Closing and will re-open if there's still an issue.
