### ISSUE TITLE
Matchups and setting lineups 

### ISSUE THREAD

**Issue by sotelocody** [bwentzloff/afs#86]
There is no way to set your lineup and every week is shows the same 2 teams playing each other. 
![E1485E07-C29B-47DC-B838-350378CD2C60](https://user-images.githubusercontent.com/61271407/74919235-49696600-5398-11ea-9ea0-d4e5c0c81bd1.png)
![5E52A8B0-3B86-4A50-9984-AFAAACBF5BE5](https://user-images.githubusercontent.com/61271407/74919241-4c645680-5398-11ea-89c9-bd0c1e51587b.png)

**Comment by bwentzloff** [comment]
Should be good now.

**Comment by sotelocody** [comment]
Can you fix the win and losses we technically didn’t play any matches
because we were having trouble setting up our lineup

**Comment by sotelocody** [comment]
Maybe do the wins and losses by total points scored by all of everyone’s
players for week one and two?
