### ISSUE TITLE
Bug: Process Waivers does not check to see if a player is still on the team before processing the Pickup/Drop

### ISSUE THREAD

**Issue by m9115m** [bwentzloff/afs#88]
STR:
Pre-Conditions:
Create a Team A with a full roster (i.e. all positions and bench full)

FROM the PLAYERS TAB
1.)  Choose a player to pickup and select a player to drop   (Waiver 1)
2.)  Choose a second player to pickup and select the **same** player to drop  (Waiver 2)
(This is a common scenario when multiple teams are vying for the same players.  In this case, I choose two players to pickup - with my preferred choice first - but they are both to replace the same player currently on the team, in case another team has a higher waiver priority.)

FROM the PROCESS WAIVERS TAB
1.)  Grant Waiver 1
2.)  Grant Waiver 2

FROM the ROSTER TAB
1.)  View Roster for Team A
(Note that the number of players now exceeds the maximum defined in the settings) - BUG

Thoughts...
It appears that Grant Waiver does not check to see if the dropped player is still on the roster, before adding a new player to the team.
In this case, the same player was selected for the drop - which is a expected - but when Wavier 1 was Granted, the dropped player was no longer on the team, invalidating the Grant for Waiver 2.

Possible Fix?
When Grant is clicked, could the code check the roster before processing the Grant, and then, if the player is no longer on the Roster, display a message "Grant can not be Processed _**Dropped Player Name**_ is no longer on the **_Team Name_** Roster.  This waiver request must be Denied"?

Thanks again, for a great app

**Comment by bwentzloff** [comment]
Thank you very much for the level of detail in this. I’ll get this fixed as soon as possible.

**Comment by m9115m** [comment]
Appears to be fixed.  There's now a popup that forces you to drop someone, in order to add a second player.  Found a related bug #123  in when writing to the Log
