### ISSUE TITLE
Enhancement:  Hourglass

### ISSUE THREAD

**Issue by m9115m** [bwentzloff/afs#90]
Would it be possible to switch the cursor from the arrow to the hourglass, when the code makes call backs to the server, and switch back when after the data fetch is complete?

Right now, the pages are refreshing slowly.  Folks likely clicking multiple times, because they are not sure if they clicked.  Suspect the multiple clicks could be adding more load to the server.

Thanks again for a great app

**Comment by bwentzloff** [comment]
Yeah. I have a very similar thing coming out hopefully tomorrow.

**Comment by m9115m** [comment]
Is there anyway to trigger some kind of change of the cursor while the page is processing?  Many of the page updates cause the page to hang.  It's almost like you need to trigger the hour glass after each click.
