### ISSUE TITLE
Team Scoring Clarification

### ISSUE THREAD

**Issue by bojangles394** [bwentzloff/afs#93]
How is “team qb” scoring calculated with regards to teams using dual quarterbacks on the same play or not having a qb in at all on a given play or when there are two forward passes in a single play? Specifically on plays when either 2 players listed at qb on the depth chart are in the game at the same time but one lines up as a receiver or running back and scores points in some capacity, or when the snap goes directly to a rb/wr in a wildcat formation and lastly when they utilize the two forward pass rule.. what is counted towards the team qb total?

**Comment by bwentzloff** [comment]
All players listed on the stats.xfl.com pages under quarterbacks count towards team QB points

**Comment by bojangles394** [comment]
Thanks Brian
