### ISSUE TITLE
"Fix Matchups" button Issue

### ISSUE THREAD

**Issue by RoyalRumbleFFL** [bwentzloff/afs#95]
Thanks again for all you do to make XFL Fantasy football possible!  

Is there something that can be done to help the "Fix Matchup" button NOT be so easily pushed on accident.  I am not sure if I have accidentally touched it but my matchups page has changed a few times this past week.  I assume because I accidentally touch it.  Some buttons like the "Leave League" button have a secondary fail safe that says something like "are you sure you want to leave the league?"  And you have to push that button also in order to complete the desired action. 
If others have had the same issue, I was able to keep hitting the "Fix Matchup" button until I got the correct combo of previous weeks that matched what was there previously.  
As weeks go by this will be harder to remember off of memory the order and matchups of all previous weeks.  
And it sets your standings board to all teams having all ties.  
Sorry for being long winded. 

Thanks,  ROYAL RUMBLE FFL

**Comment by bwentzloff** [comment]
Thanks for the suggestion. I have added a secondary fail safe like leave league has.

**Comment by RoyalRumbleFFL** [comment]
Nice work. thanks!

**Comment by bwentzloff** [comment]
It should be going again now. Sorry about the trouble.

**Comment by RoyalRumbleFFL** [comment]
You guys are impressive!  THANKS SO MUCH!!!!

**Comment by RoyalRumbleFFL** [comment]
This is the ROYAL RUMBLE FANTASY FOOTBALL LEAGUE again.

The last guy (at the turn ) had Knox drafted for both of his last picks.
Can you please take Knox off from the second time he was picked?
Thanks!!!

**Comment by bwentzloff** [comment]
What would you like me to switch the second pick to?

**Comment by RoyalRumbleFFL** [comment]
Hey,  great first week!!!

IS THERE A WAIVER WIRE?  If so where can we find it?
Thanks,

**Comment by bwentzloff** [comment]
Yup. You’ll see the option on the Players tab here in a couple hours when we are officially in week 2. On Feb 19, 2023, at 11:40 PM, RoyalRumbleFFL ***@***.***> wrote:﻿
Hey,  great first week!!!

IS THERE A WAIVER WIRE?  If so where can we find it?
Thanks,

**Comment by RoyalRumbleFFL** [comment]
Right now On our league we are able to add/drop plates Before week 2 starts
without the waiver wire.

Will owners not be able to do that when week 2 starts (and from that point
forward)?

And how is the waiver order determined?

Thank you.

**Comment by bwentzloff** [comment]
Week 2 is going now. Try refreshing your page and you should see the waiver buttons. Waivers are FAAB so they go to the highest bid.

**Comment by RoyalRumbleFFL** [comment]
So guys in my league are seeing that they have FAAB waivers when adding a
free agent.
But when I (the commish) go to add a player I don’t see any FAB or waivers,
it just adds the player I wanted.  And I made sure that “show commissioner
tools” is NOT selected.
I want to make sure that I am playing like the other owners.
Thanks!

**Comment by bwentzloff** [comment]
Try refreshing the page. It shouldn’t be letting you do that.

**Comment by RoyalRumbleFFL** [comment]
Cool. Now we are good
Thanks again.  You guys are great!!!

**Comment by RoyalRumbleFFL** [comment]
I made like 4 or 5 waiver claims. At first when I would add 2nd or 3rd
claim they would appear at the bottom of the pop-up when I would go to do
the next one.
Then I went to do one more and they didn’t appear there anymore.
Another owner was asking how he can see the claims he already made.
Are the gone or is there another way to view them?

Thankyou ,
ROYAL RUMBLE commish.

**Comment by bwentzloff** [comment]
I’ll take a look at that today.

**Comment by RoyalRumbleFFL** [comment]
Any luck with that waiver wire issue?

**Comment by bwentzloff** [comment]
I’ll be looking at it today.

**Comment by RoyalRumbleFFL** [comment]
Is there a way that we Can make it so that in WEEK 9 our top 4 teams go to
the semi finals (1 vs 4 / 2 vs 3?
And that our 5th and 6th place teams play for “NOT LAST”?

And in week 10 winning teams from semi finals play for the championship and
loosing teams from week 10 play for 3rd place?

Thanks for your time.  And the league is going well!

-Royal Rumble Commish

**Comment by bwentzloff** [comment]
Yup. Commissioners will be able to adjust playoffs with any consolation rounds they want to do.

**Comment by RoyalRumbleFFL** [comment]
Hi, I’m the commish of the Merica Fantasy Football League (USFL)
and of the Royal Rumble Fantasy Football league (XFL).  Loving both
leagues!
One of our teams forgot to insert their QB this week. We have Team QB set
up. The “Show commissioner tools” on the rosters page won’t let me put the
team’s (MAGA MEN) QB in because the game already played. Am I missing
something or is that something you have to do for us?
The teams have already agreed that they are good with the change.

Thanks!
Shad Oakes (Commish)

**Comment by bwentzloff** [comment]
Let me know what QB they want started and I’ll slot them in for you.

**Comment by RoyalRumbleFFL** [comment]
Team MAGA MEN need Stallions QBs in the QB slot.  Thank you!

**Comment by bwentzloff** [comment]
Alright, it should show up in a minute for you. Enjoy the games!

**Comment by RoyalRumbleFFL** [comment]
Thanks for the great USFL season for our league (Merica Fantasy Football
League).
Is it possible for you add the playoffs and championship to our league. We
would like to play through those weekends.

Thank you,
Commissioner Shad Oakes

**Comment by bwentzloff** [comment]
I will do my best to get that set up this week but can’t make any guarantees I will get it done in time.

**Comment by RoyalRumbleFFL** [comment]
Thanks!  You guys have been awesome!!!

**Comment by RoyalRumbleFFL** [comment]
Hey guys,
I hope you all are well.  I don’t mean to be a pest but Any word on
extending our league through playoffs and championship?
Thanks

**Comment by bwentzloff** [comment]
Let me know what the matchups should be for this weekend and I will set them up for you.

**Comment by RoyalRumbleFFL** [comment]
Awesome! Is that already manageable on our site right now or coming soon?

**Comment by RoyalRumbleFFL** [comment]
Oops,  I think I just responded to an old email from you.  But just now saw
this one. Sorry about that.

Ok so I’ll give you our teams and our lineups this evening if that’s ok.

**Comment by bwentzloff** [comment]
That works. If you get them to me tonight, I’ll have them set up first thing in the morning.

**Comment by RoyalRumbleFFL** [comment]
There are only 2 teams in our little head to head league.
MAGA MEN vs. GOP
is that good enough.  Will we be able to change players and set lineups?

**Comment by bwentzloff** [comment]
Week 11 should show up for you sometime this morning. You’ll probably have to refresh the page to see it.

**Comment by RoyalRumbleFFL** [comment]
Thanks Brian.
We got it!  We put the correct players that we drafted on each team but it
won’t let us set the lineups😬

**Comment by bwentzloff** [comment]
I think things are taking a little bit to work through the system. Try again in an hour. If it’s still not working, let me know.

**Comment by RoyalRumbleFFL** [comment]
All is good for our USFL playofffs week 11. Thank you.
Just a heads up, in our CFL leage (Hoser Fantasy Football League) some of
our players points are appearing in the scores and some aren’t.

Thanks again on our USFL!!!😁

**Comment by bwentzloff** [comment]
Are you guys seeing stats coming in for week 11? Also, are you looking to have a matchup for the championship game, as well?

CFL stats should be up to date now. They are a pain this year as the CFL’s official stats are half broken for some reason.

**Comment by RoyalRumbleFFL** [comment]
Yes points are coming through for USFL week 11.

Yes we were wanting to have a matchup for the championship game as well.
Thanks.

For CFL: my Winnipeg Kicker points aren’t there and for the other team
Shawn Bane Jr.’s pints aren’t there.

Thanks for checking in on us!!!

**Comment by RoyalRumbleFFL** [comment]
Could you please bring back up our week 11 scores?  And I don’t think it
ever showed both of our QB teams (breakers and Stallions)

Thanks again for all you do!!!😬

**Comment by bwentzloff** [comment]
Week 11 and 12 should appear in the week dropdown menu for you now if you refresh the page.

**Comment by RoyalRumbleFFL** [comment]
In the scores page I don’t see week 11 or 12. I refreshed several times but
still don’t see them.

**Comment by bwentzloff** [comment]
I forgot you were a total points league. I will update it this morning.

**Comment by RoyalRumbleFFL** [comment]
Sorry to bug you again. Hopefully it’s the last time for USFL.
We cat insert a few players into their positions in the lineup.
Thanks again for the help

**Comment by bwentzloff** [comment]
So some you can and some you can’t? Could you let me know a bit more detail?On Jun 29, 2023, at 11:25 AM, RoyalRumbleFFL ***@***.***> wrote:﻿
Sorry to bug you again. Hopefully it’s the last time for USFL.

We cat insert a few players into their positions in the lineup.

Thanks again for the help



On Wed, Jun 28, 2023 at 4:38 AM Brian Wentzloff ***@***.***>

wrote:



> I forgot you were a total points league. I will update it this morning.

>

**Comment by RoyalRumbleFFL** [comment]
Some players have the drop down box to select which place you want them in
the lineup or bench. The others don’t have the box. Instead it says Game
has started. Player is locked.

**Comment by bwentzloff** [comment]
Sorry about that. It should be fixed now.

**Comment by RoyalRumbleFFL** [comment]
Alright,  we were able to set our lineups for the USFL championship game.
THANK YOU

IN THE LINEUPS It shows stallions players vs. Showboats on Saturday at 4pm
ET and Maulers players vs. Generals on Saturday at 1pm ET.
Will that affect the scoring or is that ok?

**Comment by bwentzloff** [comment]
That’s ok

**Comment by RoyalRumbleFFL** [comment]
Cool!!! Thanks for all your help! Have a good weekend!

**Comment by RoyalRumbleFFL** [comment]
I’m assuming you are hearing this from other leagues too but Both leagues
(USFL and cfl) have some player scores appearing and some not from
yesterday.

**Comment by bwentzloff** [comment]
You are the only ones doing USFL so let me know what is missing. CFL scores are all checked after the last game which is tomorrow for this week. On Jul 2, 2023, at 9:48 AM, RoyalRumbleFFL ***@***.***> wrote:﻿
I’m assuming you are hearing this from other leagues too but Both leagues

(USFL and cfl) have some player scores appearing and some not from

yesterday.

**Comment by RoyalRumbleFFL** [comment]
Ok. I was wondering if we were. Thanks for putting up with us.
For USFL it is Stallions QBs and Maulers QBs. The rest of the players look
good.
Thanks again and again!

**Comment by RoyalRumbleFFL** [comment]
We are missing a few score from CFL WEEK 4.

WPG - QBs
SSK - Jamal Marrow
MTL - K

BC - QBs
WPG - K

Thanks for the help.

**Comment by RoyalRumbleFFL** [comment]
Each week we are missing scores. Usually QBs.
This week (7)
- Steam Rollers are missing BC QBs
- Royal Mounties are missing WPG QBs and Taquan Mizzell BC RB

FYI: It has been happening each week to a few players. But we are trying
not to bug you guys.

Thanks, Shad


Thanks for your help.
