### ISSUE TITLE
Bug:  Matchup/Line Up Popup Displaying the Incorrect Calculation for Receptions

### ISSUE THREAD

**Issue by m9115m** [bwentzloff/afs#97]
STR:
1.)  Click on the Matchups Tab
2.)  Click on View Matchup or Set Your Lineup 
3.)  Scroll to a player with Receptions

**Expected** Rececptions score displayed to be as per the defined (League points for Rececptions) * (Number of Receptions)

**Actual Result:**  Reception calculated value appears to be displaying the number of rececptions

Notes:
This league is using the default scoring value for receptions of 0.5

In the attached screen shots, note that the total calculated score for each player is correct.  Only the displayed value for Rececptions is incorrect.

Thanks again for a great App.

![Screenshot_2020-02-23_12-32-14](https://user-images.githubusercontent.com/16707058/75119684-f1518e80-5639-11ea-8ff4-e5e576a2bac4.png)
![D-Smith Receptions](https://user-images.githubusercontent.com/16707058/75119826-58237780-563b-11ea-8299-cecdec7b4d38.png)
![C-ArtisPayne Receptions](https://user-images.githubusercontent.com/16707058/75119829-5f4a8580-563b-11ea-8d85-32b9f37d767c.png)

**Comment by bwentzloff** [comment]
Thanks. All the values on the Matchup/Lineup page just show raw values of the associated stats, not fantasy points. It’s really confusing. I’m in the process of overhauling the whole thing and it will be much easier to read next weekend.

**Comment by m9115m** [comment]
Thanks Brian

Look forward to the update.

Will go ahead and close this one.
